package com.board.spring.yoony.error;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum ErrorCode {
  BAD_REQUEST(400, "COMMON.ERR.400", "BAD REQUEST"),
  NOT_FOUND(404, "COMMON.ERR.404", "PAGE NOT FOUND"),
  INTER_SERVER_ERROR(500, "COMMON.ERR.500", "INTER SERVER ERROR"),

  // ARTICLE
  ARTICLE_ID_NOT_VALID(400, "ARTICLE.ERR.400.1.1", "ARTICLE ID NOT VALID"),
  ARTICLE_PASSWORD_NOT_VALID(400, "ARTICLE.ERR.400.1.2", "ARTICLE PASSWORD NOT VALID"),
  ARTICLE_INSERT_NOT_VALID(400, "ARTICLE.ERR.400.2", "ARTICLE INSERT NOT VALID"),
  ARTICLE_UPDATE_NOT_VALID(400, "ARTICLE.ERR.400.3", "ARTICLE UPDATE NOT VALID"),


  ARTICLE_NOT_FOUND(404, "ARTICLE.ERR.404", "ARTICLE NOT FOUND"),

  ARTICLE_INSERT_FAIL(500, "ARTICLE.ERR.500.1", "ARTICLE INSERT FAIL"),
  ARTICLE_UPDATE_FAIL(500, "ARTICLE.ERR.500.2", "ARTICLE UPDATE FAIL"),
  ARTICLE_DELETE_FAIL(500, "ARTICLE.ERR.500.3", "ARTICLE DELETE FAIL"),

  // FILE
  FILE_NOT_FOUND(404, "FILE.ERR.404", "FILE NOT FOUND"),
  FILE_INSERT_FAIL(500, "FILE.ERR.500.1", "FILE INSERT FAIL"),

  // COMMENT
  COMMENT_ID_NOT_VALID(400, "COMMENT.ERR.400.1", "COMMENT ID NOT VALID"),
  COMMENT_CONTENT_NOT_VALID(400, "COMMENT.ERR.400.2", "COMMENT CONTENT NOT VALID"),
  COMMENT_NOT_FOUND(404, "COMMENT.ERR.404", "COMMENT NOT FOUND"),
  COMMENT_INSERT_FAIL(500, "COMMENT.ERR.500.1", "COMMENT INSERT FAIL"),

  ;

  private int status;
  private String errorCode;
  private String message;
}